
<div class="printess-designer" id="printessDesigner">

    <div data-role="loader" class="printess-designer-preloader-wrapper"><div class="printess-designer-preloader"></div></div>

    <button class="show-layouts-button btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#layoutOffcanvas" aria-controls="layoutOffcanvas">
        <?php echo __('Change Layout'); ?>
    </button>

    <div class="offcanvas offcanvas-start" data-bs-backdrop="false" tabindex="-1" id="layoutOffcanvas" aria-labelledby="offcanvasLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasLabel">Layouts</h5>
            <button type="button" class="btn-close text-reset" id="closeLayoutOffCanvas" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div id="layoutSnippets" class="offcanvas-body"></div>
    </div>

    <div class="offcanvas" tabindex="-1" id="cartOffcanvas" aria-labelledby="offcanvasLabel">

        <div data-role="loader" class="printess-designer-preloader-wrapper hidden"><div class="printess-designer-preloader"></div></div>

        <div class="offcanvas-header">
            <h5 id="cartOffcanvasLabel" class="fs-2 text-muted text-light"><?php echo __('Your order'); ?></h5>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <div class="offcanvas-body small" id="offcanvasBody">

            <div class="container-fluid">
                <div class="row mb-4">
                    <div class="col fs-4 fw-bold">
                        <?= $block->getName() ?>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col" id="designerProductPrice">&nbsp;</div>
                </div>
                <div class="row mb-4">
                    <div class="col">
                        <div class="input-group">
                            <button class="btn btn-secondary shadow-none" type="button" id="designerQuantityDec">-</button>
                            <input type="text" class="form-control text-center shadow-none" value="1" id="designerQuantity" />
                            <button class="btn btn-secondary shadow-none" type="button" id="designerQuantityInc">+</button>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="d-grid">
                            <button class="btn btn-primary btn-lg" id="designerAddToCart"><?php echo __('Add to Cart'); ?></button>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

    <!-- MAIN PRINTES UI-COMPONENTS -->
    <div id="printess-desktop-grid">
        <nav id="desktop-pagebar"></nav>
        <div id="desktop-properties"></div>
        <div id="desktop-printess-container"></div>
    </div>

</div>

<script type="text/x-magento-init">
    {
       "*": {
            "Digitalprint_PrintessDesigner/js/printess": {
                "session": <?= $block->getSession() ?>,
                "printess": <?= $block->getJsonConfig() ?>
            }
       }
    }
</script>

<?= $block->getPriceTemplate() ?>
