<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_printess = $this->helper(Digitalprint\PrintessDesigner\Helper\Printess::class); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_sku = $_product->getSku(); ?>

<?php $buttonTitle = $_printess->hasTemplate($_sku) ? __('Design Now') : __('Add to Cart'); ?>

<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    <?php if (!$_printess->hasTemplate($_sku)) :?> id="product-addtocart-button" disabled<?php endif; ?>>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            <?php if ($_printess->hasTemplate($_sku)) :?>"Magento_Catalog/product/view/validation": {
                "bindSubmit": false
            },<?php endif; ?>
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
