<?php
/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
<?php $_printess = $this->helper(Digitalprint\PrintessDesigner\Helper\Printess::class); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_sku = $_product->getSku(); ?>

<div class="product-add-form">
    <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
          action="<?= $block->escapeUrl($block->getSubmitUrl($_product)) ?>" method="<?php if ($_printess->hasTemplate($_sku)) :?>get<?php else :?>post <?php endif; ?>"
          id="product_addtocart_form"
          <?php if ($_product->getOptions() && !$_printess->hasTemplate($_sku)) :?> enctype="multipart/form-data"<?php endif; ?>>
        <?php if (!$_printess->hasTemplate($_sku)) :?>
            <input type="hidden" name="product" value="<?= (int)$_product->getId() ?>" />
            <input type="hidden" name="selected_configurable_option" value="" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
            <input type="hidden" name="item"  value="<?= (int)$block->getRequest()->getParam('id') ?>" />
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getChildHtml('form_top') ?>
        <?php else: ?>
            <input type="hidden" name="sku" value="<?= $_product->getSku() ?>" />
            <?php foreach ($_printess->getStartDesign($_sku) as $_key => $_val): ?>
                <input type="hidden" name="startDesign[<?= $_key ?>]" value="<?= $_val ?>" />
            <?php endforeach; ?>
        <?php endif; ?>
        <?php if (!$block->hasOptions()) :?>
            <?= $block->getChildHtml('product_info_form_content') ?>
        <?php else :?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1') :?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>
        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2') :?>
            <?= $block->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?php if (!$_printess->hasTemplate($_sku)) :?>
            <?= $block->getChildHtml('form_bottom') ?>
        <?php endif;?>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-<?= $block->escapeHtml($_product->getId()) ?>]": {
            "priceBox": {
                "priceConfig":  <?= /* @noEscape */ $block->getJsonConfig() ?>
            }
        }
    }
</script>
